### ISSUE TITLE
Multitenant integration doesn't work out of the box

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Extensions.DependencyInjection#1]
Not sure if this is an issue for multitenancy, for this library, or for... something else.

The original question is asked and answered [over on StackOverflow](http://stackoverflow.com/questions/38940241/autofac-multitenant-in-an-aspnet-core-application-does-not-seem-to-resolve-tenan/38960122#38960122).

The problem:

When request services are set up as part of the ASP.NET hosting pipeline, it happens too early for a tenant to be determined so multitenant DI doesn't work.

I found a workaround by manually resolving the service scope factory and setting this up but it seems like there should be a better/easier way. At the very least, we need to document the workaround, but it'd be nice if things "just worked."
- Do we need to file an issue with the ASP.NET team? Would they be open to adding some sort of factory method to their `RequestServicesContainerMiddleware`? Or is this something we need to provide?
- Do we need another package to supply the workaround middleware as part of the pipeline for people that want it? What would we call that?

A complete walkthrough of the pipeline is explained [in the answer on StackOverflow](http://stackoverflow.com/questions/38940241/autofac-multitenant-in-an-aspnet-core-application-does-not-seem-to-resolve-tenan/38960122#38960122).

**Comment by marcrocny** [comment]
I'm starting to take a look at this.  Some questions.  

* Was this behavior induced by [this commit on aspnet/hosting](https://github.com/aspnet/Hosting/commit/b6a3fee08869cd9ac9d266b15b4eb7de205199ed)?  Any chance of us getting them to roll it back?
* Could the answer be as simple as providing an alternate implementation of `IServiceScopeFactory` that does "lazy" resolution of the scope?

**Comment by tillig** [comment]
Yeah, it does appear that commit is what caused it. I don't know off hand if creating some sort of "lazy" implementation would fix it because the whole race condition is around the timing of when the scope gets created. It may be that instead of [AutofacServiceScope](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacServiceScope.cs#L45) taking in the child lifetime scope it belongs to that it should take in the _parent_ scope and only create the child scope when the `ServiceProvider` property is accessed - at the last possible moment.

It'd be worth a shot to try it out.

**Comment by marcrocny** [comment]
Another thought on the way to puzzling this out: posing this as a "timing" or "race condition" issue seems to obscure the problem.  To me it looks more like a symptom of the impedance mismatch between MS DI and Autofac.  Specifically, the distinctions that MS DI makes between service provider, scope factory and scope don't really have an analogue in Autofac as separate entities.  For resolving `IServiceProvider` and `IServiceScopeFactory`, Autofac just hands back the current scope (`IComponentContext and ILifetimeScope being the same in this context); the scope factory implementation just begins another scope; and the `AutofacServiceScope.ServiceProvider` is just itself (`this._lifetimeScope.Resolve<IServiceProvider>();` takes a dependency on IComponentContext, which when resolved returns the current lifetime scope).  For the most part this just works.  In the "vanilla" case, resolving `IServiceScopeFactory` from the application-root `IServiceProvider` just wraps the root lifetime scope, and all is well.

Where this breaks down with `MutlitenantContainer` is that there is no *single, injectable* `ILifetimeScope` to act as the scope-factory.  Resolving `ILifetimeScope` from the MTC immediately resolves the tenant scope.

It's not a case of "too soon," it seems like more of a case of "only once".  Not sure if this is getting me closer to a solution.  Checking to see if middleware constructor dependencies on `IServiceProvider` are resolved or just handed the root provider returned by `ConfigureServices`.

**Comment by marcrocny** [comment]
PR #10 gives "space" for `RequestServicesContainerMiddleware` to resolve tenant scope, and isn't stuck with the default scope.

The remaining problem of getting `HttpContext` into an `ITenantIdentificationStrategy` implementation can be overcome by configuring the `IHttpContextAccessor` service, implementing the tenant-ID to take a dependency on it, and then resolving the tenant-ID from the underlying container before building the multitenant container.

**Comment by tillig** [comment]
After talking it over with @alexmg we're going to try to keep the Autofac.Extensions.DependencyInjection adapter really as thin as possible in order to keep it easy to maintain and as stable as possible - no special casing, etc.

We've already started [an Autofac.AspNetCore package](https://github.com/autofac/Autofac.AspNetCore) that has only the extension method now for wiring up the `IServiceProviderFactory` hooks for ASP.NET Core. We hadn't published it yet because it was only one small extension method. However, we can add the middleware noted in the StackOverflow answer to that package and make it easy to consume - a one-liner or thereabouts. It could be something you use if you need it; but if you don't, don't worry. Sort of like the `IServiceProviderFactory` support.

**Comment by tillig** [comment]
I have an idea I'm working on in the [Autofac.AspNetCore repo](https://github.com/autofac/Autofac.AspNetCore). I've set up an example web site that I'm using to test things out and try to solve some issues.

I found a couple of challenges that it seems need to be dealt with.

- **Resolving the request services from the container instead of a tenant scope.** This is the primary issue noted here, but is potentially only about 75% of the problem. Request scope definitely needs to come from the `MultitenantContainer` if it's available to ensure the tenant has a chance to get identified and get a proper request scope created.
- **Making `HttpContext` available to tenant identification.** Tenant identification in a web app is going to be largely dependent on inbound request parameters - maybe a cookie, maybe a URL component, etc. However, request services appear to get generated _before_ the standard `IHttpContextAccessor.HttpContext` property gets set. This is the other 25% of the problem.

The current experimental design requires a `WebHostBuilder` call to add an Autofac request services feature. This is how it will locate the root container/lifetime scope (the `MultitenantContainer`).

In the middleware that handles generating request services, it both sets the current `IHttpContextAccessor.HttpContext` if it hasn't already been set (so tenant can be identified) and resolves an `IServiceScopeFactory` from the root lifetime scope (the `MultitenantContainer`). This is the point at which the tenant will get identified so the lifetime scope hierarchy will be like:

- Root/MultitenantContainer
  - Tenant Scope
    - Request Scope

I'm not _super_ thrilled with having to provide an accessor for the root container, but we had to do something similar in the `Autofac.Web` integration for web forms with `IContainerProviderAccessor` and all that.

Also, for the 90% case (non-multitenant) none of this needs to be used anyway so it becomes somewhat moot.

Given `Autofac.Extensions.DependencyInjection` is useful both in ASP.NET Core and outside it, in .NET Core apps that aren't ASP.NET related, it seems to make sense to handle the specific ASP.NET challenges in a package meant for that rather than try to special-case things in the A.E.DI package. It's true that many consumers of the package are doing so for ASP.NET Core, but keeping the A.E.DI adapters as thin as possible and addressing app-type-specific needs in an app-type-specific way ensures we don't impact performance or add complexity for app types that don't need it. It also allows specific application types (like ASP.NET Core) to change how they're doing things and allow us to change the app-specific integration package to change rather than the general adapter.

**Comment by tillig** [comment]
Published [Autofac.AspNetCore.Multitenant 1.0.0](https://www.nuget.org/packages/Autofac.AspNetCore.Multitenant/) with the solution as generally outlined in the SO answer. [Autofac / ASP.NET Core integration documentation updated with info on setup.](http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#multitenant-support)

The solution wasn't included in the Autofac.AspNetCore repo since it really is pretty edge case just for multitenancy.
