### ISSUE TITLE
Problems encountered using Autofac

### ISSUE THREAD

**Issue by Linlccc** [autofac/Autofac.Extensions.DependencyInjection#101]
Program.cs
~~~
var builder = WebApplication.CreateBuilder(args);

// Use Autofac
builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Replace the default controller activator
//builder.Services.Replace(ServiceDescriptor.Transient<IControllerActivator, CustomControllerActivator>());

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseAuthorization();

app.MapControllers();

app.Run();
~~~
CustomControllerActivator.cs
~~~
public class CustomControllerActivator : IControllerActivator
{
    public object Create(ControllerContext context)
    {
        // `serviceProvider` the object is `Autofac.Extensions.DependencyInjection.AutofacServiceProvider` type
        var serviceProvider = context.HttpContext.RequestServices;
        ...
    }

    public void Release(ControllerContext context, object controller)
    {
         ...
    }
}
~~~
WeatherForecastController.cs
~~~
public class WeatherForecastController : ControllerBase
{
    private static readonly string[] Summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    private readonly ILogger<WeatherForecastController> _logger;
    private readonly IServiceScope serviceProvider;

    public WeatherForecastController(ILogger<WeatherForecastController> logger,IServiceProvider serviceProvider)
    {
        _logger = logger;
        //`serviceProvider` the object is `Autofac.Extensions.DependencyInjection.AutofacServiceProvider` type
        serviceProvider = serviceProvider;
    }

    [HttpGet(Name = "GetWeatherForecast")]
    public IEnumerable<WeatherForecast> Get()
    {
        return Enumerable.Range(1, 5).Select(index => new WeatherForecast
        {
            Date = DateTime.Now.AddDays(index),
            TemperatureC = Random.Shared.Next(-20, 55),
            Summary = Summaries[Random.Shared.Next(Summaries.Length)]
        })
        .ToArray();
    }
}
~~~

I checked the source code and didn't see you replace 'IControllerActivator' or 'IControllerActivatorProvider', so I don't quite understand how you operate the activation of the controller

I don't understand how you replace the object of 'HttpContext.RequestServices' with the type of 'Autofac.Extensions.DependencyInjection.AutofacServiceProvider'

**Thank you very much for asking for relief**

**Comment by alistairjevans** [comment]
@Linlccc, is there something not working, or are you just asking how it works behind the scenes?

The default controller activator in ASP.NET Core uses the configured ServiceProviderFactory to resolve services used by the controller. The line:

```csharp
builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
```

swaps out the default ServiceProviderFactory for the Autofac one defined in this repository. So the default controller activator will now use that.

Also worth reading the section in our docs on ASP.NET Core, specifically the section on using controllers as services, and how ASP.NET core creates the instances of controllers:

https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services

**Comment by Linlccc** [comment]
> @Linlccc，是否有什么不工作，或者你只是在问它是如何在幕后工作的？
> 
> ASP.NET Core 中的默认控制器激活器使用配置的 ServiceProviderFactory 来解析控制器使用的服务。该行：
> 
> ```cs
> 建设者。主机。UseServiceProviderFactory ( new  AutofacServiceProviderFactory ());
> ```
> 
> 用此存储库中定义的 Autofac 替换默认的 ServiceProviderFactory。所以默认的控制器激活器现在将使用它。
> 
> 还值得阅读我们关于 ASP.NET Core 的文档中的部分，特别是关于将控制器用作服务的部分，以及 ASP.NET Core 如何创建控制器实例：
> 
> https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services

**Comment by Linlccc** [comment]
> @Linlccc，是否有什么不工作，或者你只是在问它是如何在幕后工作的？
> 
> ASP.NET Core 中的默认控制器激活器使用配置的 ServiceProviderFactory 来解析控制器使用的服务。该行：
> 
> ```cs
> 建设者。主机。UseServiceProviderFactory ( new  AutofacServiceProviderFactory ());
> ```
> 
> 用此存储库中定义的 Autofac 替换默认的 ServiceProviderFactory。所以默认的控制器激活器现在将使用它。
> 
> 还值得阅读我们关于 ASP.NET Core 的文档中的部分，特别是关于将控制器用作服务的部分，以及 ASP.NET Core 如何创建控制器实例：
> 
> https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services

**Comment by Linlccc** [comment]
> @Linlccc, is there something not working, or are you just asking how it works behind the scenes?
> 
> The default controller activator in ASP.NET Core uses the configured ServiceProviderFactory to resolve services used by the controller. The line:
> 
> ```cs
> builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());
> ```
> 
> swaps out the default ServiceProviderFactory for the Autofac one defined in this repository. So the default controller activator will now use that.
> 
> Also worth reading the section in our docs on ASP.NET Core, specifically the section on using controllers as services, and how ASP.NET core creates the instances of controllers:
> 
> https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services

I want to know how he works behind the scenes
I only used one sentence of code`builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory());`，
I saw that he replaced the implementation of 'HttpContext.RequestServices' object and 'iserviceprovider' with the type of 'autofacserviceprovider'

**Comment by alistairjevans** [comment]
If I understand you correctly, the answer is somewhat complicated. There's a couple of hoops the framework makes you jump through.

The [`CreateServiceProvider` method](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacServiceProviderFactory.cs#L79) in our `AutofacServiceProviderFactory` is invoked when the app host is build, which gives ASP.NET Core an instance of a "Container Root" effectively.

Each time an HTTP request fires, the framework will resolve `IServiceScopeFactory` (which we register [here](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/553f2881712d4cabe79a1dd121a147c01da65c8a/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L105) so it resolves to  `AutofacServiceScopeFactory`.

`AutofacServiceScopeFactory` creates new instances of [`AutofacServiceScope`](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/553f2881712d4cabe79a1dd121a147c01da65c8a/src/Autofac.Extensions.DependencyInjection/AutofacServiceScope.cs#L36) when asked, which has a `ServiceProvider` property that is the actual "thing" that code is resolved from.

To be honest, anything more than that is probably a question for the MSDI team more than us; we just conform to their way of integrating Autofac to their libraries.

**Comment by Linlccc** [comment]
我写了一个测试，替换默认的 `IServiceProviderFactory` ，已经替换成功了，但是获取到的 `IServiceProvider` 的实现还是 .net 默认的
AutowiredServiceProviderFactory.cs
~~~
public class AutowiredServiceProviderFactory : IServiceProviderFactory<IServiceCollection>
{
    public IServiceProvider CreateServiceProvider(IServiceCollection containerBuilder)
    {
        var serviceProvider = containerBuilder.BuildServiceProvider();
        //  Class `AutowiredServiceProvider` is to obtain services from `serviceProvider`, so there is no other operation
        return new AutowiredServiceProvider(serviceProvider);
    }

    IServiceCollection IServiceProviderFactory<IServiceCollection>.CreateBuilder(IServiceCollection services)
    {
        if (services == null) return new ServiceCollection();
        return services;
    }
}
~~~


Then I use `builder.Host.UseServiceProviderFactory(new AutowiredServiceProviderFactory());`, but I get `HttpContext.RequestServices` objects and `IServiceProvider` implementations Asp.Net Core default `Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope` type, not my custom `AutowiredServiceProvider`

but
~~~
...
WebApplication app = builder.Build();
// 这个 `service` 是我自定义的 `AutowiredServiceProvider` 类型
var service = app.Services;
~~~

**Comment by alistairjevans** [comment]
If you have specific questions about "how do I create a custom service provider", those are best raised with the dotnet team directly (https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+DI+label%3Aarea-Extensions-DependencyInjection), rather than us. We can support for any issues with our specific provider, but we can't debug problems with non-autofac stuff I'm afraid, we just don't have the capacity.

**Comment by Linlccc** [comment]
> If you have specific questions about "how do I create a custom service provider", those are best raised with the dotnet team directly (https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+DI+label%3Aarea-Extensions-DependencyInjection), rather than us. We can support for any issues with our specific provider, but we can't debug problems with non-autofac stuff I'm afraid, we just don't have the capacity.


Maybe the way I asked is not correct. I found that you have replaced all of them in use, but I think you can use the default provider of Asp.Net Core at some time, but I can't find a way. I just want to know where you replace it, or the replacement in some places can be configured

**Comment by alistairjevans** [comment]
As I said, beyond the call made by the user to add the service provider factory, all we do is register an `IServiceScopeFactory` [here](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L105).

**Comment by tillig** [comment]
In the future **PLEASE DO NOT DOUBLE-POST.** This apparently was [also asked on StackOverflow](https://stackoverflow.com/questions/71408467/problems-encountered-using-autofac) and we already monitor there. Asking twice wastes folks' time in having to also copy/paste answers into two different places.
