### ISSUE TITLE
Have some issue with Autofac.AspNetCore.Multitenant on Autofac.Extensions.DependencyInjection Version 8.0.0

### ISSUE THREAD

**Issue by runaway1995** [autofac/Autofac.Extensions.DependencyInjection#107]
**Describe the bug**
On version **Autofac.Extensions.DependencyInjection Version 8.0.0** some bug is conected with **ITenantIdentificationStrategy**.
On this version, ITenantIdentificationStrategy always chooses null multitenant.
On version  **Autofac.Extensions.DependencyInjection Version 7.2.0** everything works correct.

**To reproduce**
Test repository: https://github.com/runaway1995/TestMultitenant
On version 8.0.0:
![image](https://user-images.githubusercontent.com/89520045/174061669-03352205-7426-43c2-8583-495aab544871.png)
On version 7.2.0:
![image](https://user-images.githubusercontent.com/89520045/174061743-b91afa2f-90fa-409d-925c-cae05b665692.png)

**Assembly/dependency versions:**
```xml
<ItemGroup>
      <PackageReference Include="Autofac" Version="6.4.0" />
      <PackageReference Include="Autofac.AspNetCore.Multitenant" Version="5.1.0" />
      <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="8.0.0" />
      <PackageReference Include="Autofac.Extras.Moq" Version="6.1.0" />
    </ItemGroup>
```

Could you fix it, please?

**Comment by tillig** [comment]
Already on it: https://github.com/autofac/Autofac.AspNetCore.Multitenant/issues/43
