### ISSUE TITLE
Should transient objects be externally owned by default?

### ISSUE THREAD

**Issue by vitolpoc** [autofac/Autofac.Extensions.DependencyInjection#108]
**Describe the bug**
Disposable transient objects are held onto forever and a memory leak occurs.

**To reproduce**
1. Register a disposable transient class
2. Resolve the class 100 times
3. Look into a memory dump and you will see 100 instances being held by  Disposer._items

**Full exception with stack trace:**
N/A

**Assembly/dependency versions:**
Latest

**Additional context**
I think transient disposables should be managed by the consumer.  There is no way for me to configure this through your APIs.

Why would you hold onto every transient object?  

**Proposed Fix**
`c#
 AutofacRegistration.cs

 private static IRegistrationBuilder<object, TActivatorData, TRegistrationStyle> ConfigureLifecycle<TActivatorData, TRegistrationStyle>(
        this IRegistrationBuilder<object, TActivatorData, TRegistrationStyle> registrationBuilder,
        ServiceLifetime lifecycleKind,
        object lifetimeScopeTagForSingleton)
    {
        switch (lifecycleKind)
        {
            case ServiceLifetime.Singleton:
                if (lifetimeScopeTagForSingleton == null)
                {
                    registrationBuilder.SingleInstance();
                }
                else
                {
                    registrationBuilder.InstancePerMatchingLifetimeScope(lifetimeScopeTagForSingleton);
                }

                break;
            case ServiceLifetime.Scoped:
                registrationBuilder.InstancePerLifetimeScope();
                break;
            case ServiceLifetime.Transient:
                registrationBuilder.InstancePerDependency()
                                             **.ExternallyOwned()**; // This is the "fix".
                break;
        }

        return registrationBuilder;
    }`

**Comment by tillig** [comment]
Disposable objects have always been owned by the container as a way to ensure they don't get disposed too early. It's why we have [a note to always resolve from a lifetime scope](https://autofac.readthedocs.io/en/latest/lifetime/disposal.html) instead of the root container whenever possible. This is also a requirement to be compatible with the Microsoft DI container, [which has disposal as a specification test](https://github.com/dotnet/runtime/blob/e398ba2490014e5c04ed4c60980acbda6619f356/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L464).

There is no plan to make any change here.

**Comment by vitolpoc** [comment]
Thanks for the response. 

I think scopes are verbose and I dont link depending on a container in all of my services.  I would prefer to use "auto factories", hence the use of this frarmework.

It would be helpful to allow us to externally configure this through some options.

As an example...

`public Constructor(Container container) => _container = container;

await using (var scope = _container.BeginLifetimeScope())
{
    var service = scope.Resolve<MyComponent>():

    // DisposeAsync will be called on MyComponent
    // when the using block exits.
}
`

vs 

`Public Constructor(Func<MyComponent> factory) => _factory = factory;

await using var service = _factory();
`

**Comment by tillig** [comment]
You can inject `ILifetimeScope` automatically into constructors without having to register it. It may be worth taking some time to go through the docs and see all the features available; the stuff you're asking about isn't really "advanced knowledge" for Autofac and there is plenty of doc and examples to explain how to get done what you're looking to do.
