### ISSUE TITLE
Improved compatibility with autofac ecosystem.

### ISSUE THREAD

**Issue by pengweiqhca** [autofac/Autofac.Extensions.DependencyInjection#122]
**Is your feature request related to a problem? Please describe.**
I want to integrate `Autofac.Extensions.DependencyInjection` and `Autofac.Extras.DynamicProxy`.

**Describe the solution you'd like**
1. Add a interface
``` C#
public interface IRegistrationCallback
{
    void OnRegister<TActivatorData, TRegistrationStyle>(
        IRegistrationBuilder<object, TActivatorData, TRegistrationStyle> registration);
}
```
2. Add a override method of `AutofacRegistration.Populate`
3. Call `OnRegister` method after `ConfigureLifecycle`
``` diff
-   builder
+   var rb = builder
        .RegisterGeneric(implementationType)
        .ConfigureServiceType(descriptor)
        .ConfigureLifecycle(descriptor.Lifetime, lifetimeScopeTagForSingletons);

+   registrationCallback?.OnRegister(rb);
```
4. I will create a custom `IServiceProviderFactory<ContainerBuilder>` type and call the new `Populate` method.

**Describe alternatives you've considered**

**Additional context**

**Comment by tillig** [comment]
I have to be honest, I don't know that this is something we want. The point of this library is to basically translate Microsoft registrations back into Autofac, which it does. If folks want to use build callbacks, they should be using the Autofac registration syntax where it's already available. That includes possibly moving type registrations out of Microsoft syntax and into Autofac if needed.

This is the same reason there's no "bridge" to any other Autofac-specific support - adapters, decorators, interceptors, and so on. Folks who want Autofac constructs should use Autofac.
