### ISSUE TITLE
Consider subscribing to ApplicationStopped event before returning the ServiceProvider

### ISSUE THREAD

**Issue by bruno-garcia** [autofac/Autofac.Extensions.DependencyInjection#13]
The docs suggest the _possibility_ of subscribing to ApplicationStopped event. I'm finding difficult to find a use-case where we wouldn't want to have the ApplicationStopped event call the container's Dispose method.

In case we confirm that the decision of subscribing _Container.Dispose_ to _ApplicationLifetime.AppliactionStopped_ should be the default behavior, I suggest adding this before returning adapter _AutofacServiceProvider_.

One issue with it is that the package would now depend on _Microsoft.AspNetCore.Hosting_

**Comment by tillig** [comment]
Given the Microsoft.Extensions.DependencyInjection package is used in more than just ASP.NET Core projects, we won't do that here.

We plan on splitting the docs a bit to make that more clear - .NET Core vs. ASP.NET Core.
