### ISSUE TITLE
'Detected package downgrade' warning message when targeting net461 framework

### ISSUE THREAD

**Issue by KoshelevS** [autofac/Autofac.Extensions.DependencyInjection#16]
Hi,

There is a warning message when using `Autofac.Extensions.DependencyInjection` package in dotnet core project with `net461` target framework: `Detected package downgrade: NETStandard.Library from 1.6.1 to 1.6.0. Reference the package directly from the project to select a different version`. This message appears when trying to do `dotnet restore` in project's folder.

Environment:
- dotnet core SDK: 1.0.4
- target framework: net461
- package version: 4.2.0

Steps to reproduce:
1. Execute `dotnet new console -o autofac.testapp` command to create new project.
2. Change `TargetFramework` to `net461` in the `autofac.testapp.csproj` file.
3. Add the following code to the `autofac.testapp.csproj` file:
```
  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.0" />
  </ItemGroup>
```
4. Execute `dotnet restore` command in project's folder.

NB: `dotnet restore` command executed under dotnet core SDK 2.0 produces similar **error** message instead of the warning.

**Comment by tillig** [comment]
Did you try what the warning mentioned and add a direct reference to NETStandard.Library 1.6.1?

**Comment by gschuager** [comment]
Installing NETStandard.Library 2.0.0 solved the issue for me, but I understand we shouldn't be required to do that.

**Comment by KoshelevS** [comment]
@tillig Yep.

It gives me another warning: `A PackageReference for 'NETStandard.Library' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs` in my multitargeted library: `<TargetFrameworks>netstandard2.0;net461</TargetFrameworks>`.

The following fixes both warnings, but looks a little bit odd:
```
  <ItemGroup Condition="'$(TargetFramework)' == 'net461'">
    <PackageReference Include="NETStandard.Library" Version="2.0.0" />
  </ItemGroup>
```

Anyway, thanks for the tip :)
