### ISSUE TITLE
Update for .NET Standard/Core 2.0

### ISSUE THREAD

**Issue by vandensd** [autofac/Autofac.Extensions.DependencyInjection#17]
Is there a plan to update this package for .NET Core 2.0 or .NET Standard 2.0 and have documentation up to date?

**Comment by tillig** [comment]
Should be compatible. Is there a specific problem?

**Comment by vandensd** [comment]
No, didn't realize it would be backward compatible.  I'm doing a migration from 1.1 and it seems to be fine so far.  Thank you.
