### ISSUE TITLE
Current level of support

### ISSUE THREAD

**Issue by ipjohnson** [autofac/Autofac.Extensions.DependencyInjection#21]
Hi @alexmg and @tillig 

I've seen a number of comments over the past year questioning the quality of integration between Autofac and ASP.Net core. I was under the impression that the issue has been resolved and autofac's integration was complete. Is this not the case?

Thanks
-Ian

**Comment by tillig** [comment]
I dunno, seems to work fine for us. I use it pretty much daily at work (online banking systems) and it's never failed me yet. Can you be more specific about "quality of integration?" Is this that... _continued conversation_ over in the issue-I-won't-link-to-with-an-overly-long-and-branching-set-of-topics?

We had trouble with order of registration/resolution for a while but that was fixed before we released. If there's something else, you'll need to be more specific.

**Comment by ipjohnson** [comment]
You are correct I didn't want to ask in that thread for a myriad of reasons ...

From the couple times I've used it everything worked great and I was under the impression that the issue originally discovered (like enumerable order and what not) had been ironed out. 

I just wanted to get my facts as I've seen a number of posts from certain people stating that autofac has trouble integrating with ASP.Net core and it's the exact opposite of my experience. 

Thanks
