### ISSUE TITLE
Autofac is not configured if Startup class inherited from StartupBase

### ISSUE THREAD

**Issue by xakep139** [autofac/Autofac.Extensions.DependencyInjection#23]
When `Startup` class is inherited from `StartupBase` the `ConfigureContainer()` method is not called (checked in debug). After removing the inheritance injecting works perfectly.
I use ASP.NET Core 2.0 with `Autofac.Extensions.DependencyInjection` (version 4.2.0) and `Microsoft.AspNetCore.All` (version 2.0.0).

Program.cs:
```
public class Program
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseKestrel()
            .ConfigureServices(services => services.AddAutofac())
            .UseStartup<Startup>()
            .Build();
}
```

Startup.cs:
```
public class Startup : StartupBase
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public override void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();
    }

    public void ConfigureContainer(ContainerBuilder builder)
    {
        builder.RegisterType<object>();
    }

    public override void Configure(IApplicationBuilder app)
    {
        app.UseMvc();
    }
}
```

**Comment by tillig** [comment]
The selection and calling of startup methods happens in `Microsoft.AspNetCore.Hosting` [in the `StartupLoader` class.](https://github.com/aspnet/Hosting/blob/964b671288d95ee659d2119f3c3d9831c70b81db/src/Microsoft.AspNetCore.Hosting/Internal/StartupLoader.cs) That's not something Autofac controls.

[I'd recommend filling an issue over there.](https://github.com/aspnet/Hosting/issues)
