### ISSUE TITLE
ASP.NET Core 2.0.0

### ISSUE THREAD

**Issue by dazinator** [autofac/Autofac.Extensions.DependencyInjection#24]
Microsoft have released a bunch of packages for ASP.NET Core 2, like `EF Core 2.0.0` - which all depend on `Microsoft.Extensions.DependencyInjection` version `2.0.0` or greater.

They install just fine into you application, alongside `Autofac.Extensions.DependencyInjection` - it just means `Microsoft.Extensions.DependencyInjection` package is bumped to version 2.0.0.

However when you run your application, the dependencies that are built against version < 2.0.0 (like  `Autofac.Extensions.DependencyInjection` ) cause an exception to be thrown. See: https://github.com/aspnet/EntityFrameworkCore/issues/8498

The recommended answer was to update all dependencies to reference `Microsoft.Extensions.DependencyInjection` version 2.0.0 :-(

**Comment by dazinator** [comment]
Would you accept a PR for this?

**Comment by tillig** [comment]
Have you tried adding an explicit reference to Microsoft.Extensions.DependencyInjection from your app?

**Comment by dazinator** [comment]
Yep

**Comment by tillig** [comment]
Problem is if we update this we become explicitly incompatible with earlier .NET Core, which isn't cool. Do you have a very simple repro app for this?

**Comment by dazinator** [comment]
> Do you have a very simple repro app for this?

I will put one together.

**Comment by dazinator** [comment]
Hmm.. it looks like `Autofac.Extensions.DependencyInjection` might be ok, because it doesn't appear to call  `BuildServiceProvider()` anywhere. The problem occurs when a library compiled against `Microsoft.Extensions.DependencyInjection` v1.1 ends up calling `BuildServiceProvider()` and `Microsoft.Extensions.DependencyInjection` at runtime is actually v2.

I have a library that depends on `Autofac.Extensions.DependencyInjection` - but it's my library that ends up calling `BuildServiceProvider()` - so it's actually my library that needs to be re-compiled against v2, and `Autofac.Extensions.DependencyInjection` get's away with it :-) 

I am only 90% certain at the moment, have yet to prove this fully. I will re-open this issue if I hit a problem for which I can provide a repro.

**Comment by dazinator** [comment]
Here is the most basic repro that shows the issue. Just run the console app: https://github.com/dazinator/Repros/tree/BuildServiceProvider

This should confirm that `Autofac.Extensions.DependencyInjection` should be unimpacted as long as it doesn't make any calls to `BuildServiceProvider`

**Comment by tillig** [comment]
Thanks for taking the time to narrow this down. Looks like we should be good to go for the time being. Glad you located the culprit!
