### ISSUE TITLE
Cannot make EntityFramework DbContext work with Autofac on .net core 2

### ISSUE THREAD

**Issue by epitka** [autofac/Autofac.Extensions.DependencyInjection#28]
Try StackOverflow! If you have a _usage question_ ("How do I...?" "Others have this working but I can't get it...") please try [StackOverflow](http://stackoverflow.com) and tag your question `autofac`. We, along with a great community, monitor those questions.

**Have you [read the docs?](http://autofac.readthedocs.io/)**
yes

**This repo is for Autofac.Extensions.DependencyInjection only.** If you are encountering issues with another package (MVC, Web API, etc.) or core Autofac, please file it in the appropriate repo. Thanks!

**When filing an issue, please include:**
Two projects, API and Domain

API dependencies are:

```
> 
> <ItemGroup>
>     <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.0" />
>     <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="4.0.0" />
>     <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
>     <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.2" />
>     <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="1.1.0" />
>     <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="1.1.0" />
>     <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="1.1.0" />
>   </ItemGroup>
```
and Domain

```
 <ItemGroup>
    <PackageReference Include="Autofac" Version="4.6.2" />
    <PackageReference Include="MediatR" Version="4.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" />
  </ItemGroup>
```

Issue I am experiencing is on stackoverflow @
[https://stackoverflow.com/questions/48747982/why-am-i-getting-error-cannot-access-disposed-object-in-net-core-2-with-ef-a/48749321?noredirect=1#comment84502729_48749321](url)

**Comment by tillig** [comment]
If it's on SO you don't need to file an issue.
