### ISSUE TITLE
AutofacServiceProvider does not implement IDisposable

### ISSUE THREAD

**Issue by DaveVdE** [autofac/Autofac.Extensions.DependencyInjection#3]
I'm finding that my SingleInstance registered instances are not disposed after my ASP.NET web app closes. I narrowed it down to where the host is supposed to dispose of the ServiceProvider and it seems it tries to cast the provided ServiceProvider to `IDisposable`:

https://github.com/aspnet/Hosting/blob/dev/src/Microsoft.AspNetCore.Hosting/Internal/WebHost.cs#L215

Since AutofacServiceProvider does not implement IDisposable, there's no way for the host to dispose of the root container, causing my instances to remain undisposed.

**Comment by tillig** [comment]
[Our integration docs show how to handle disposing the container at app shutdown.](http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html)

**Comment by DaveVdE** [comment]
Fair enough, that's the work-around I came up with myself.

Care to explain why this isn't integrated?

**Comment by tillig** [comment]
Disposing the container isn't the same as disposing the service provider. Not everyone wants both at the same time and you can't make it optional.

There are a lot of differences in the way the "default" Microsoft container/provider works vs. how various implementers (us, SimpleInjector, StructureMap, etc.) implemented the interfaces. We abide by the interfaces, but there are subtle things where every container differs. This is one - if the service provider is supposed to be disposed, they should have put IDisposable on it. They didn't, so it's an undocumented implicit behavior for the default container, not actually part of the provider implementation contract.

There's a _lot_ more like this. If you're interested in the discussion, follow along here: https://github.com/aspnet/DependencyInjection/issues

**Comment by DaveVdE** [comment]
Thanks, that makes it clear.

**Comment by smarts** [comment]
@tillig I don't understand this part:
> you can't make it optional.

Why not? .NET has made disposal optional in the case of `StreamReader`. There's a Boolean value specified in constructor which determines whether stream's lifetime operates in conjunction w/ the lifetime of the reader or is controlled externally. Why is Autofac opposed to that notion?
