### ISSUE TITLE
Unable to resolve IOptions<T> from child container

### ISSUE THREAD

**Issue by dazinator** [autofac/Autofac.Extensions.DependencyInjection#32]
I am using:

```
	<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.3.0" />
```

~~I will submit a PR with a failing test case / repro.~~ See repro: https://github.com/autofac/Autofac.Extensions.DependencyInjection/pull/33

The issue I am having, is occuring when trying to use the `Options` pattern, provided by `Microsoft.Extensions.Options`.

The issue is, if I register these services in the root container, everything works.
If I don't register these services in the root container, but instead create a child lifetime scope, and register these services in the child lifetime scope only, then try to resolve an `IOptions<T>` from that child scope, it errors.

Message:

> Message: Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OptionsManager`1 (ReflectionActivator), Services = [Microsoft.Extensions.Options.IOptions`1[[Dotnettency.Tests.MyOptions, Dotnettency.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Microsoft.Extensions.Options.OptionsManager`1[Dotnettency.Tests.MyOptions]' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions] factory' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions])'. (See inner exception for details.)
---- Autofac.Core.DependencyResolutionException : None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Microsoft.Extensions.Options.OptionsManager`1[Dotnettency.Tests.MyOptions]' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions] factory' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions])'.

Stack Trace:

at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Dotnettency.Tests.AutofacOptionsTests.CanResolveTOptionsFromChildContainer() in F:\Repos\Dotnettency\src\Dotnettency.Tests\AutofacOptionsTests.cs:line 49
----- Inner Stack Trace -----
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
Result Message:	
Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = OptionsManager`1 (ReflectionActivator), Services = [Microsoft.Extensions.Options.IOptions`1[[Dotnettency.Tests.MyOptions, Dotnettency.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Microsoft.Extensions.Options.OptionsManager`1[Dotnettency.Tests.MyOptions]' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions] factory' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions])'. (See inner exception for details.)
---- Autofac.Core.DependencyResolutionException : None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Microsoft.Extensions.Options.OptionsManager`1[Dotnettency.Tests.MyOptions]' can be invoked with the available services and parameters:
Cannot resolve parameter 'Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions] factory' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptionsFactory`1[Dotnettency.Tests.MyOptions])'.

**Comment by tillig** [comment]
I vaguely recall there's something in the chain of registrations for MS options that really wants to be a singleton. I'm on my phone and can't dive in now.

A good next step is to unwind what is actually in the meta call to register options. It can't resolve `OptionsManager<T>` so how is that being registered?

This sort of usage is pretty edge case and there are a lot of issues to resolve. No promises on a speedy resolution here; a PR with the solution is likely your fastest way to get it solved.

**Comment by dazinator** [comment]
@tilling thank you for the suggestions. I'll do my best to investigate further. 
Just to get down my current thinking if I get time to come back to this: `services.AddOptions()` and `services.Configure()` generate `ServiceDescriptors` and AutoFac `Populate()`  then does the necessary autofac registrations. When populating a root container all works. When populating a child container - resolution fails. There mist be something causing registrations not to be handled the same at child lifetime scope level compared to root level. Perhaps some special casing at root level in autofac code.

**Comment by dazinator** [comment]
Think I am honing in on the problem.

These are the service descriptors in the service collection - you can see IOptions<T> is forwarded to the singleon `OptionsManager<T>`, and that `IOptionsFactory<T>` is forwarded to `OptionsFactory<T>` as transient.

![image](https://user-images.githubusercontent.com/3176632/44659635-cbbfd680-a9fc-11e8-8156-3f8a890a6167.png)

The singleton `OptionsManager<T>` seemingly takes `IOptionsFactory<T>` as a constructor param (which is transient)

The error as shown by the stack trace is that Autofac can't resolve `IOptionsFactory<T>` which it needs to construct the singleton `OptionsManager<T>`.

> Cannot resolve parameter 'Microsoft.Extensions.Options.IOptionsFactory`1[Autofac.Extensions.DependencyInjection.Test.AutofacRegistrationTests+TestOptions] factory' of constructor 'Void .ctor(Microsoft.Extensions.Options.IOptionsFactory`1[Autofac.Extensions.DependencyInjection.Test.AutofacRegistrationTests+TestOptions])'. (See inner exception for details.)

I am not sure why Autofac cannot resolve `IOptionsFactory<T>` at this point, given that this service is registered as transient as shown in the screenshot.

I am also wondering if the `DefaultConstructorFinder` that is being used is correct, I need to compare what gets used when populating the root container. I know structuremap has a special asp.net core constructor finder.

**Comment by dazinator** [comment]
Ok this looks like it might be a problem.
One difference between the child container, and the root container, after populating with the same service descriptors, is that:


The child container is missing a "Registration"that the root container has.

Child: 

![image](https://user-images.githubusercontent.com/3176632/44661345-51925080-aa02-11e8-8d6b-435c4b3c9ad7.png)

Root:

![image](https://user-images.githubusercontent.com/3176632/44661370-6242c680-aa02-11e8-8498-be03b13040f6.png)

I have no idea what this `ConfigureNamedOptions` registration is or why it is missing on the child container at this point, but it sounds important.

**Comment by dazinator** [comment]
Bingo that was it.

**Comment by dazinator** [comment]
PR #33 submitted.
