### ISSUE TITLE
Spec test for public-no-arg generic constraint fails

### ISSUE THREAD

**Issue by jbogard** [autofac/Autofac.Extensions.DependencyInjection#40]
See https://github.com/aspnet/Extensions/pull/536/commits/66a64ba8fcd7d90b395f8a0af45d2a0b04be4b42#diff-e37d6761fa5732546952f42a605c42ebR14

I'm adding support for constrained open generics to the base DI package. This package fails one of the spec tests added for public no-arg constraints. I've verified that resolving in the base package does work:

```c#
public class NewConstrained<T> : ISingleGeneric<T>
    where T : new()
{
}

public class ClassWithNew
{
}

[Fact]
public void CanResolveMultipleServicesWhenConstrainedWithNewConstraint()
{
    var builder = new ContainerBuilder();

    builder.RegisterGeneric(typeof(NewConstrained<>)).As(typeof(ISingleGeneric<>));
    builder.RegisterGeneric(typeof(CGeneric<>)).As(typeof(ISingleGeneric<>));

    var container = builder.Build();

    Assert.Equal(2, container.Resolve<IEnumerable<ISingleGeneric<ClassWithNew>>>().Count());
    Assert.Single(container.Resolve<IEnumerable<ISingleGeneric<string>>>());
}
```

That test passes in Autofac. However, this new spec test fails:

```c#
[Fact]
public void PublicNoArgCtorConstrainedOpenGenericServicesCanBeResolved()
{
    // Arrange
    var collection = new TestServiceCollection();
    collection.AddTransient(typeof(IFakeOpenGenericService<>), typeof(ClassWithNoConstraints<>));
    collection.AddTransient(typeof(IFakeOpenGenericService<>), typeof(ClassWithNewConstraint<>));
    var provider = CreateServiceProvider(collection);
    // Act
    var allServices = provider.GetServices<IFakeOpenGenericService<PocoClass>>().ToList();
    var constrainedServices = provider.GetServices<IFakeOpenGenericService<ClassWithPrivateCtor>>().ToList();
    // Assert
    Assert.Equal(2, allServices.Count);
    Assert.Equal(1, constrainedServices.Count);
}
```

Stack trace:

```c#
[xUnit.net 00:00:01.36]     Autofac.Extensions.DependencyInjection.Test.SpecificationTests.PublicNoArgCtorConstrainedOpenGenericServicesCanBeResolved [FAIL]
Failed   Autofac.Extensions.DependencyInjection.Test.SpecificationTests.PublicNoArgCtorConstrainedOpenGenericServicesCanBeResolved
Error Message:
 Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IFakeOpenGenericService`1[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[Microsoft.Extensions.DependencyInjection.Specification.Fakes.IFakeOpenGenericService`1[[Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithPrivateCtor, Microsoft.Extensions.DependencyInjection.Specification.Tests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.Extensions.DependencyInjection.Specification.Tests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> GenericArguments[0], 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithPrivateCtor', on 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithNewConstraint`1[T]' violates the constraint of type 'T'. (See inner exception for details.)
---- System.ArgumentException : GenericArguments[0], 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithPrivateCtor', on 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithNewConstraint`1[T]' violates the constraint of type 'T'.
-------- System.TypeLoadException : GenericArguments[0], 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithPrivateCtor', on 'Microsoft.Extensions.DependencyInjection.Specification.Fakes.ClassWithNewConstraint`1[T]' violates the constraint of type parameter 'T'.
Stack Trace:
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider) in C:\dev\aspnet-extensions\src\DependencyInjection\DI.Abstractions\src\ServiceProviderServiceExtensions.cs:line 79
   at Microsoft.Extensions.DependencyInjection.Specification.DependencyInjectionSpecificationTests.PublicNoArgCtorConstrainedOpenGenericServicesCanBeResolved() in C:\dev\aspnet-extensions\src\DependencyInjection\DI.Specification.Tests\src\DependencyInjectionSpecificationTests.cs:line 615
----- Inner Stack Trace -----
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Autofac.Features.OpenGenerics.OpenGenericServiceBinder.TryBindServiceType(Service service, IEnumerable`1 configuredOpenGenericServices, Type openGenericImplementationType, Type& constructedImplementationType, IEnumerable`1& constructedServices)
   at Autofac.Features.OpenGenerics.OpenGenericRegistrationSource.<RegistrationsFor>d__3.MoveNext()
   at Autofac.Core.Registration.ComponentRegistry.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.ComponentRegistry.RegistrationsFor(Service service)
   at Autofac.Features.Collections.CollectionRegistrationSource.<>c__DisplayClass0_0.<RegistrationsFor>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
----- Inner Stack Trace -----
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
```

My PR isn't merged, so this is contingent on my PR getting merged. If you fix this behavior, you'll want to open a PR with the MS DI package to remove that part about skipping this test.

**Comment by tillig** [comment]
I see what the test is aiming for, but admittedly it's sort of odd. Like, in this case, last in wins - `IFakeOpenGenericService<>` will, if you resolve a single thing instead of the set, be backed by `ClassWithNewConstraint<>` which has a `new()` constraint on `T`. The `new()` constraint requires a public constructor. By trying to resolve `ClassWithNewConstraint<ClassWithPrivateCtor>` you actually _would_ get an exception because it doesn't fulfill the requirements. Thus, the premise of the test is kind of wrong - it's OK to resolve collections of things and maybe skip ones that are invalid by definition... but if you try to resolve just a single instance it's not OK?

Should I comment on the PR? I'd like to get some clarification about what the intent is here. Ignore constraints in collections but not in individual resolutions?

**Comment by jbogard** [comment]
The overall behavioral intent is to throw if constraints aren't met for single registrations (which should be rare for open generics), but skip for collections.

That way if you declare a dependency on a single `IFoo<T>` and the only implementation doesn't satisfy the `T` constraint, it should throw rather than have a null dependency.

However, if you resolve `IEnumerable<IFoo<T>>`, then it should skip those that don't fulfill the constraint, also allowing empty collections.

It's a bit odd - only the test with a `new()` constraint fails. All the other scenarios `class, struct, IFoo, AbstractClass` all work.

**Comment by jbogard** [comment]
You're not registering closed handlers, though. More like decorators.

I register a bunch of decorators, but some have generic constraints, so that when I resolve the collection I only get the decorators that match the constraint. Autofac does this today. Except with this one constraint, and through this package.

For us at least, constrained decorators are pretty common. I'd rather do:

`public class AuditLogger<T> : ILogger<T> where T : IAuditable`

than

`public class AuditLogger : ILogger<IAuditable>`

Since the latter you lose the original `T` type. Then when you resolve you're doing `container.Resolve<IEnumerable<ILogger<T>>>()`

**Comment by tillig** [comment]
Decorators in Autofac are more explicit than just registering an open generic. It's kind of a separate concept. You can register a decorator on an open generic, but if the constraint around the thing it's decorating can't be satisfied, you'll get an exception rather than an empty set of decorated things. Especially if the thing I'm registering/resolving isn't a decorator, I'd really want to know that when I resolve there's a problem.

**Comment by jbogard** [comment]
Ah, gotcha - this isn't for decorators, that was a common example of open generics.

It's really for enumerables of open generics. Validators are a better example. When you resolve validators, you don't want the one `IValidator<T>`, you want *all* validators that can satisfy that closed type of `IValidator<Foo>`.

**Comment by tillig** [comment]
I'd agree you want all `IValidator<Foo>` but if you registered a validator that won't handle `Foo` because of one-off open generic constraints, isn't that sort of a violation of Liskov? "I am a validator but you can't treat me like any other `IValidator<T>` because I only validate things of a certain type." Especially if `IValidator<T>` isn't where the constraint is. I mean, I get it, I understand the appeal of getting that collection and ignoring constraints, I just don't know that's how I'd be expecting a system to work.

**Comment by jbogard** [comment]
I dunno about Liskov, but think of this more as a way to do pattern matching with DI. I don't want to lose the original type, because now I can't have that `IValidator<T>` take any dependencies on `T`-specific things.

For us, this is the number one design issue of the base DI package of why we adopt say StructureMap. Just about every project I'm on will at some point use constrained open generics as a means to provide the ability to register services that match specific characteristics. The consumers then don't care about those characteristics. That's why this is just pattern matching via DI.

**Comment by tillig** [comment]
Circling back from the PR, it appears this may be added to the base/default container but not added to the spec.

**Comment by alsami** [comment]
> Circling back from the PR, it appears this may be added to the base/default container but not added to the spec.

Should we move this issue to the autofac repository then?

**Comment by tillig** [comment]
I don't think there's any action to take here. We can probably just close it. I don't believe we have any intention of implementing the behavior here.
