### ISSUE TITLE
asp.net core web DiagnosticListener invokes onActivated twice 

### ISSUE THREAD

**Issue by HeroXXiv** [autofac/Autofac.Extensions.DependencyInjection#41]
Hi,

I would like to add a module to attach every resolved component to its own context, using a ConditionalWeakTable. Everything works fine until I added this module to an asp.net core web app.

Most of the components onActivated/onActivating once, but DiagnosticListener does twice with the same resolved context.

Is there any reason could describe this behavior, or shouldn't I attach components and contexts like this?

netcore ver 2.0/2.1
Autofac ver 4.8.1/4.9.0-beta1
Autofac.Extensions.DependencyInjection ver 4.3.1

```csharp
    public class Startup
    {
        public IContainer ApplicationContainer { get; private set; }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            var builder = new ContainerBuilder();
            builder.Populate(services);

            builder.RegisterModule(new TestModule());

            ApplicationContainer = builder.Build();
            return new AutofacServiceProvider(ApplicationContainer);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }

    class TestModule : Module
    {
        private readonly ConditionalWeakTable<object, IComponentContext> _contextMap = new ConditionalWeakTable<object, IComponentContext>();

        protected override void AttachToComponentRegistration(IComponentRegistry componentRegistry, IComponentRegistration registration)
        {
            registration.Activated += (i, e) =>
            {
                var context = e.Context.Resolve<IComponentContext>();
                var instance = e.Instance;

                if (_contextMap.TryGetValue(instance, out var attached))
                {
                    Assertion.IsTrue(typeof(DiagnosticListener) == instance.GetType());
                    Assertion.IsTrue(attached == context);
                    return;
                }

                _contextMap.Add(instance, context);
            };
        }
    }
```

**Comment by tillig** [comment]
This is going to take a bit of time to trace out and, I'll be honest, if you wait for us to do it you won't get a timely answer. If I had to guess, is say something in the ASP.NET Core framework is... Maybe registering two manually created instances of DiagnosticListener?

The way to figure this out is to look at the contents of the IServiceCollection coming in to ConfigureServices. Find all the DiagnosticListener registrations in there and work backwards. What's different about them? Are they instances or factories or something? How many are there? Where in ASP.NET did they get registered?

Yes, that's a lot of work and spelunking into code that isn't yours. It's not ours, either, which is why we won't be able to dive into this any time soon.

Hope that helps.

**Comment by HeroXXiv** [comment]
thx for your reply.

i digged a little deeper, in asp.net core [source](https://github.com/aspnet/AspNetCore/blob/5665d78ffe6c2e414c42548facfe3e6375192f4e/src/Hosting/Hosting/src/WebHostBuilder.cs#L270), `DiagnosticListener` is registered like
```csharp
    // public class DiagnosticListener : DiagnosticSource, IObservable<KeyValuePair<string, object>>, IDisposable
    var listener = new DiagnosticListener("Microsoft.AspNetCore");
    services.AddSingleton<DiagnosticListener>(listener);
    services.AddSingleton<DiagnosticSource>(listener);
```

i tried to use autofac's register logic, which leads to same result.
```csharp
    // class Derived : Base
    var bean = new Derived();
    builder.RegisterInstance(bean).As<Base>().SingleInstance();
    builder.RegisterInstance(bean).As<Derived>().SingleInstance();
```

i think i should try another way to attach components and their context, that will be another question.
