### ISSUE TITLE
How to get built container in asp net core 3.0 preview 8

### ISSUE THREAD

**Issue by Caskia** [autofac/Autofac.Extensions.DependencyInjection#53]
Hi,
   I had read [doc](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/README.md) carefully. If configured like this method, there is no way to get 
built container. I need a reference to the built container for more flexibility. Do you have any idea?

aspnetcore version: 3.0.0-preview8.19405.7
Autofac version: 4.9.4
Autofac.Extensions.DependencyInjection version: develop branch

**Comment by alsami** [comment]
Hi, does [this ](https://github.com/autofac/Examples/tree/master/src/AspNetCore3Example)help you? We currently do not have updated the docs for it. We will do so with the final release.

**Comment by Caskia** [comment]
Thanks for your so much quick response. I have solved the problem through your comment.
