### ISSUE TITLE
how to get the current scope on asp.net core

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.Extensions.DependencyInjection#6]
_From @xLabel on November 3, 2016 9:17_

on mvc3/4 , we can using Autofac.Integration.Mvc.AutofacDependencyResolver to get current lefttime, like the picture example. But now is on asp.net core , the new platform is using 'Autofac.Extensions.DependencyInjection.AutofacServiceProvider' to set in .
i must get the current scope to resolve the same instance.  (which is registertype is InstancePerLifetimeScope) .

please help !!!
![image](https://cloud.githubusercontent.com/assets/3363613/19960534/6f460b4a-a1e8-11e6-8764-c57d20cab5f9.png)

_Copied from original issue: autofac/Autofac#808_

**Comment by tillig** [comment]
There's no explicit way to get the `ILifetimeScope` for the request. You can use `HttpContext.RequestServices` in ASP.NET Core to resolve request lifetime items.

Additional questions on how ASP.NET Core dependency resolution and registration works should probably be directed to the ASP.NET Core team given it's the same regardless of the backing container.

**Comment by JorgeSanc** [comment]
how do you resolver this problem???
