### ISSUE TITLE
Components registered with RegisterInstance are only Dispose()d or DisposeAsync()ed when actually used

### ISSUE THREAD

**Issue by Tragetaschen** [autofac/Autofac.Extensions.DependencyInjection#68]
Is this for Autofac 5?
Yes

**Have you [read the docs?](https://autofac.readthedocs.io/)**
Yes, the one about [instance components](https://docs.autofac.org/en/latest/register/registration.html#instance-components)

```csharp
builder.RegisterInstance(new MyAsyncDisposable());
builder.RegisterInstance(new MyDisposable());
```
With just these registrations and no other components that require `MyAsyncDisposable` or `MyDisposable`, neither component is properly disposed when disposing the container. (yes, my use case is more complex than that... :)

As a workaround, I can add a `.AutoActivate()` to the registration. This marks the instance as used.

If it matters, this is an ASP.NET Core 3.1 application during graceful shutdown (`IHostApplicationLifetime.StopApplication()`).

**Comment by alistairjevans** [comment]
Thanks @tillig; it does sound pretty similar. From what I can tell, the behaviour is as expected with Autofac, and behaves according to the docs you referenced.

ASP.NET Core docs for the default DI suggest that singleton instances are not disposed of when registered (i.e. they are ExternallyOwned by default); I wonder if the ASP.NET Core host doesn't dispose of the top-level container in an expected way? Not sure.

**Comment by tillig** [comment]
Another couple of tests that would be interesting - is it just `RegisterInstance` or do `Register` and `RegisterType` also fail to dispose?

```c#
builder.Register(ctx => new MyDisposable());
builder.RegisterType<MyDisposable>();
```

You may need to change how you track when dispose is called in the tests. For example, increment a counter when dispose is called rather than using a static instance.

**Comment by Tragetaschen** [comment]
I had played around with these registration types. The thing is that both only create an instance when one is actually used while RegisterInstance hands over the instance to Autofac regardless of any actual usage.

I have created an `MyDisposableUser` that expects a `MyDisposable` in the constructor:
```csharp
builder.RegisterInstance(Program.MyDisposable);
builder.RegisterType<MyDisposableUser>();
```
When I do not request an instance of `MyDisposableUser`, Dispose is not called.
When I request an instance for example as parameter of the `Startup.Configure` method or by extending the `MyDisposableUser` registration with `.AutoActivate()`, Dispose is called.

**Comment by Tragetaschen** [comment]
I have been running from the sources of Autofac and Extensions using the release tags. Here's likely some old news:
When running bare Autofac (as in the test above), the provided instance is disposed by
- the container's `ComponentRegistry`
- or the _rootLifetimeScope

depending on whether it's bare / unused or auto-activated (startable) / used. The instance flows from the former to the latter when required.

For the Extensions integration, there are several `AutofacServiceProvider` (six in the reproduction with `.AutoActivate()`  created, the first for the container and the remaining for some `LifetimeScopes`. Of those six only two get disposed. The others are still active when `IHost.Run` returns in Main.

![image](https://user-images.githubusercontent.com/1947968/73767666-06907700-4778-11ea-9b73-83070c4d7323.png)

Since the provider holding the container is never disposed, the component registry is never disposed and when the registered instance is never activated (startable or otherwise), it remains in the registry and is ignored.

ASP.NET Core's hosting seems to be missing out on a number of AutofacServiceProvider.Dispose() calls…

**Comment by Tragetaschen** [comment]
For reference, [this is the AutofacServiceProvider holding the Container](https://github.com/dotnet/extensions/blob/v3.1.1/src/Hosting/Hosting/src/HostBuilder.cs#L233
). It remains as member in the HostBuilder and is never disposed :-(

CC: @davidfowl

**Comment by Tragetaschen** [comment]
This then does the trick:
```csharp
#nullable enable

// after IHost.Run[Async]() has returned:
await hostBuilder.Fixup_AsIAsyncDisposable().DisposeAsync();

// somewhere accessible
public static IAsyncDisposable Fixup_AsIAsyncDisposable(this IHostBuilder hostBuilder)
{
    var type = hostBuilder.GetType();
    var field = type.GetField("_appServices", BindingFlags.Instance | BindingFlags.NonPublic)!;
    var appServices = field.GetValue(hostBuilder)!;
    return (IAsyncDisposable)appServices;
}
```
But obviously I would not recommend that.

Of the six AutofacServiceProviders created in the reproduction, there are two that are disposed by the framework. The above code disposes the root one holding the Container instance which in turn disposes all the lifetime scopes held by the remaining three providers which remain undisposed.

**Comment by davidfowl** [comment]
Can you file a bug on hosting with an small repro of the problem?

**Comment by alistairjevans** [comment]
@Tragetaschen, from the latest updates on the dotnet/extensions issue, it appears as though there may be an issue that is going to get fixed, but there may be an Autofac workaround? Is that a good summary? Do you think it's worth us putting a workaround in for this problem, or should we wait?

**Comment by Tragetaschen** [comment]
Thanks for asking, but thinking about an answer I realized that I'm missing a lot of context like how many people actually rely on 100% correct dispose behavior, how much effort a workaround entails, and how it's maintained in the future.

As far as I understand, there is a discrepancy here between how Hosting expects DI integration to work and how Autofac's integration actually works. There is the brittle workaround above for now and I activated it with `#if NETCOREAPP3_1` to force a reevaluation of the situation with the next release.

I would probably push to try to figure out if and how future versions of Hosting are changing before doing an interim or maybe necessary fix.

**Comment by Tragetaschen** [comment]
A PR to the Hosting extension just closed the runtime bug.

Long story short: The `IHost` implementation was created through Autofac and the `IServiceProvider` constructor argument was resolved to a child scope by Autofac. The "unwritten assumption" though was that that `IServiceProvider` would be the same instance as the one residing in the `IHostBuilder`. Their fix is to make sure that assumption holds by explicitly using it when constructing the `IHost` implementation while still properly resolving the other parameters.

Disposal is then handled by the `IHost` implementation.

So with the release of .NET 6, the issue should be gone. Since nobody upvoted any of the two issues, I would say there is no need for an Autofac interim fix. Feel free to reopen if you think otherwise.
