### ISSUE TITLE
Blazor 3.2 setup problem

### ISSUE THREAD

**Issue by RedDeathGitHub** [autofac/Autofac.Extensions.DependencyInjection#69]
Hi friends!

A while ago you helped me with a working setup for Blazor WebAssembly, and it worked great.
But, things change, and Blazor released a new version:
_https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/_

And it changed the setup.
Now the one which is described here in your docs:
_https://autofaccn.readthedocs.io/en/latest/integration/blazor.html_
does not work anymore.

I would like to know what to do now - if there is a specific library I should use or how to update an existing _Program.cs_.

Before we took advantage of _UseServiceProviderFactory_ method, but id does not exist anymore.

My code now looks something like this:
```
public static WebAssemblyHostBuilder CreateHostBuilder(string[] args)
        {
            var builder =  WebAssemblyHostBuilder.CreateDefault();
            builder.RootComponents.Add<App>("app");
            // This does not exist anymore
            //builder.UseServiceProviderFactory(new AutofacServiceProviderFactory(b => b.RegisterModule<ClientModule>()))

            var services = builder.Services;
            services.AddBlazoredLocalStorage();
            services.AddAuthorizationCore();

            JobManager.UseUtcTime();

            return builder;
        }
```

Please help me, I can't go forward without Autofac! ❤️ 
Also, if you manage to get it working, please update the docs for other lost souls like me.

**Comment by alistairjevans** [comment]
Wow, so it looks like there is no way to add Autofac to Blazor in that version; the WebAssemblyHostBuilder doesn't implement the necessary interfaces. 

I'm probably going to raise this as an issue on their GitHub, see if we can get to the bottom of this.

**Comment by RedDeathGitHub** [comment]
Thank you! Hopefully they will resolve it soon.
Please put the link here so I can upvote it.

**Comment by alistairjevans** [comment]
Raised at https://github.com/dotnet/aspnetcore/issues/19985.

**Comment by tillig** [comment]
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

Looks like 3.2 preview 2 is out and that issue in the ASP.NET Core repo got closed as fixed. Try upgrading to the latest to verify.

**Comment by alistairjevans** [comment]
Oh, I see; looks like the Microsoft.AspNetCore.Blazor is not in use now; they've changed the package names, that's why I didn't see the new version.

**Comment by RedDeathGitHub** [comment]
OK got it working - did not notice the package name change either 😄 

Could you please update the docs for other people also?

**Comment by harleybl** [comment]
@RedDeathGitHub, @alistairjevans - How did you get this to work?
I am using the official v3.2 from May 16th and I don't see a method called UseServiceProviderFactory on WebAssemblyHostBuilder.
I am new to Blazor so any insight would be most appreciated.

**Comment by Gaz83** [comment]
I have the same issue as @harleybl How do you get this to work?

**Comment by tillig** [comment]
Looks like it's [`WebHostAssemblyBuilder.ConfigureContainer`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.hosting.webassemblyhostbuilder.configurecontainer?view=aspnetcore-3.1#Microsoft_AspNetCore_Components_WebAssembly_Hosting_WebAssemblyHostBuilder_ConfigureContainer__1_Microsoft_Extensions_DependencyInjection_IServiceProviderFactory___0__System_Action___0__) now. I gather it'd be something like:

```c#
var builder =  WebAssemblyHostBuilder.CreateDefault();
builder.ConfigureContainer(new AutofacServiceProviderFactory());
```

I'll raise an issue on the docs repo, but there's nothing that needs to happen to Autofac.Extensions.DependencyInjection to make any of this work, it appears. It's just Microsoft moving methods around, which isn't something Autofac controls. Given that, I'm going to close this.

If folks want the docs fixed faster, or made more robust, we'd love to see a PR for better Blazor docs. I don't think any of the product owners on Autofac actually use Blazor. The integration is all done via the standard ASP.NET Core integration points, nothing "Autofac specific." It'd be nice to see some Blazor users write the docs they'd like to see.
