### ISSUE TITLE
AspNet Core 1.1 broke autofac!

### ISSUE THREAD

**Issue by ShadowDancer** [autofac/Autofac.Extensions.DependencyInjection#7]
After upgrading to Autofac 1.1 website won't start anymore. WebHostBuilder.Build() throws exception:
```Additional information: The requested service 'Microsoft.AspNetCore.Hosting.Server.IServer' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.```

It works if I remove autofac from project.

Repro:
https://github.com/ShadowDancer/AutofacNetCoreRepro

Repro steps:
Create new AspNet Core WebApplication on NetFramework
Add autofac
Update startup.cs with 
```
            var containerBuilder = new ContainerBuilder();
            return new AutofacServiceProvider(containerBuilder.Build());
```

**Comment by tillig** [comment]
You forgot the call to `builder.Populate(services)`.

**Comment by ShadowDancer** [comment]
What a shame! I made mistake in my repro, and because of that thought that it is autofac problem.

In 1.0 I was populating services, disposing created container and then creating another one with populating services. That was obviously wrong, but it worked (by accident). In 1.1 ms guys added
```
      if (this.CheckDisposed())
        throw new ObjectDisposedException("LoggerFactory");
```
in default LoggerFactory, and now creating logger crashes after disposing first container.

Sorry for bothering You.
