### ISSUE TITLE
Compatibility with Autofac v6

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Autofac.Extensions.DependencyInjection#78]
v6 Compatibility and version dependency checks ahead of release.

**Comment by alistairjevans** [comment]
All tests pass without further changes; package ref just needs updating when the actual release goes out.

**Comment by tillig** [comment]
Should we set this as a _range_ like `[5.0.0,7.0.0)` in the PackageReference rather than forcing the update?

**Comment by alistairjevans** [comment]
I haven't actually done that in a PackageReference before, but I guess we can, yeah.

**Comment by tillig** [comment]
The other alternative would be to possibly major-version this (due to the CLS compliant change in core Autofac and forcing folks to take the new update). You're sorta damned if you do, damned if you don't. Folks will complain that adding a default reference here doesn't immediately get you to v6; but folks will also complain that taking the upgrade here forced them to take a major Autofac upgrade.

**Comment by alistairjevans** [comment]
A lot of people will access Autofac now by adding this package directly to an ASP.NET Core project, without adding Autofac itself. We'd want the referenced default to be 6 ideally? I can't remember all the rules about how nuget picks the version to use, but I think it's lowest major, highest patch?

**Comment by tillig** [comment]
Yeah, if we want v6 in here by default, then let's set the min at v6 and do a major version increment here. There's not a great explanation of how semver should work with dependency updates, but I figure if we're forcing people to take a potentially breaking dependency change, this is, itself, a breaking change.

**Comment by alistairjevans** [comment]
If we're just referencing the new version in the package (as opposed to really changing any code or build options), I'm going to move this to the 'Changes in develop, Need Update to Release v6 and Merge to master' column, because we won't do any more changes until 6 is released.

**Comment by tillig** [comment]
OK, I'll buy that. I can move it now, I have it up in another tab.

**Comment by tillig** [comment]
Oh, it's already there. :) I should read the little notes between comments better.

**Comment by tillig** [comment]
Closing this since the last thing remaining (like with all the other "done" libraries) is to update to the release version of v6 and publish.

**Comment by alistairjevans** [comment]
Pushed to Nuget, tagged, and release created.
