### ISSUE TITLE
Make AutofacServiceProviderFactory & AutofacServiceScope class public

### ISSUE THREAD

**Issue by maliming** [autofac/Autofac.Extensions.DependencyInjection#85]
Is there a reason not to do this?

https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/de3276fa0d50fe310283e1e36526488654285b4e/src/Autofac.Extensions.DependencyInjection/AutofacServiceScope.cs#L36

https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/36d487749ef7184357bbc4d162bf425b8474eb36/src/Autofac.Extensions.DependencyInjection/AutofacServiceScopeFactory.cs#L36

**Comment by tillig** [comment]
The reason is that the fewer things we expose as public, the more flexibility we have to change things under the covers. As library owners, the question isn't "why _shouldn't_ we do it," but actually "why _should_ we?"

**Comment by maliming** [comment]
hi @tillig 

Thanks for your reply, My situation is when I try to customize `IServiceProviderFactory `and `AutofacRegistration `I can't access `AutofacServiceScopeFactory`. The purpose of customizing is to enable features such as property injection(`PropertiesAutowired`) for all services.

https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/4d5212d9e53b846d72c7a60f6183751713c0a4ac/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L97

**Comment by tillig** [comment]
You set property injection up on the registrations, not on the service provider. That is, it's registration-time, not resolve-time. Forcing every resolve through an `InjectProperties()` on resolve is a bad idea: you'll both get a horrible perf hit and you'll likely accidentally inject properties that shouldn't be injected.

Perhaps a more detailed explanation of your use case would help. We generally don't _want_ people customizing things like the scope factory or service provider for the same reasons you can't "derive and override" the Autofac container class itself or the `ContainerBuilder` - folks can get in some rough spots with perf and inadvertent code behavior. If there's a way to help you get what you want without this sort of extension, it'd be better to try for that. But I'm not clear on the actual use case details so I can't offer any help.

**Comment by maliming** [comment]
Thanks @tillig I will rethink my use case.
