### ISSUE TITLE
Autofac fails to resolve singleton instance of Application Insights TelemetryConfiguration

### ISSUE THREAD

**Issue by vukispasic** [autofac/Autofac.Extensions.DependencyInjection#88]
DI resolving TelemetryClient and TelemetryConfiguration objects for Microsoft Application Insights doesn't work properly with Autofac

## Steps to Reproduce

Application insights is plugged in to services as recommended by Microsoft in Startup class:

```c#
public void ConfigureServices(IServiceCollection services)
{
  services.AddApplicationInsightsTelemetry(o => o.InstrumentationKey = "instrumentation key goes here");
}
```

AutofacServiceProviderFactory is used as container builder

```c#
Host.CreateDefaultBuilder(args)
  .UseServiceProviderFactory(new AutofacServiceProviderFactory())
  .ConfigureWebHostDefaults(webBuilder =>  
  {
    webBuilder.UseStartup<Startup>();
  });
```

When injecting TelemetryConfiguration in class constructor, resolved instance is not correct resolved by AutofacServiceProvider, ApplicationIdProvider, InstrumentationKey properties are empty:

![image](https://user-images.githubusercontent.com/14116321/114420860-01695c00-9bb5-11eb-916a-6a76d4475a37.png)

When I try to resolve instance with Microsoft default provider, correct instance is resolved

![image](https://user-images.githubusercontent.com/14116321/114420972-1a720d00-9bb5-11eb-8863-5eb47c1d773b.png)

## Expected Behavior

Expected behavior is having singleton instance resolved as registered by calling AddApplicationInsightsTelemetry method listed above. When correct instance is resolved then insights get sent to Azure, otherwise output window shows message that telemetry client is unconfigured and insights are not sent to Azure because there is no instrumentation key. 

This is source code of ApplicationInsightsExtensions class from application insights library which is used to register application insights on startup:

https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/bfccb57e4f632fa2ee627dacedeaa55644c739f5/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsExtensions.cs

https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/bfccb57e4f632fa2ee627dacedeaa55644c739f5/NETCORE/src/Shared/Extensions/ApplicationInsightsExtensions.cs

The registration of TelemetryConfiguration is performed in method AddTelemetryConfigAndClient:

```c#
private static void AddTelemetryConfigAndClient(IServiceCollection services)
{
  services.AddOptions();
  services.AddSingleton<IOptions<TelemetryConfiguration>, TelemetryConfigurationOptions>();
  services.AddSingleton<IConfigureOptions<TelemetryConfiguration>, TelemetryConfigurationOptionsSetup>();
  services.AddSingleton<TelemetryConfiguration>(provider => provider.GetService<IOptions<TelemetryConfiguration>>().Value);
  services.AddSingleton<TelemetryClient>();
}
```

## Dependency Versions

Autofac version used is 6.0.0
Microsoft.ApplicationInsights.AspNetCore - 2.15.0
Project  target framework - .NET Core 3.1

**Comment by tillig** [comment]
I'm going to update the original issue text to use [code fences in the Markdown](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) so it's easier to read.

**Comment by tillig** [comment]
For reference, it appears the code for the App Insights integration [has moved to this repo](https://github.com/microsoft/ApplicationInsights-dotnet). It may or may not have changed much.

Before we can continue, we need to know more about the dependency versions you are on:
- What is the target framework for your project?
- What Application Insights dependency version(s) are you using?
- What Autofac (and related) version(s) are you using? (Pretty sure it's not 2.15.)

**Comment by vukispasic** [comment]
Sorry, I fixed the Autofac version, it is 6.0.0. Application insights library is 2.15.0

What is the target framework for your project? .net core 3.1
What Application Insights dependency version(s) are you using? 2.15.0
What Autofac (and related) version(s) are you using? 6.0.0

**Comment by alsami** [comment]
Would you be so kind to provide a small sample for reproducing that issue? I would look into it then.
Sounds strange, given the extension is just using `IOptions<TelemetryConfiguration>` to register a function factory singleton in order to be able to resolve`TelemetryConfiguration`.

**Comment by vukispasic** [comment]
Hello Alsami

I managed to fix the issue, the problem was in my code - "hidden" double registration of TelemetryConfiguration that was causing that correct singleton instance get resolved. I will close this issue. I am sorry for false alert
