### ISSUE TITLE
Add full framework target

### ISSUE THREAD

**Issue by adamhathcock** [autofac/Autofac.Extensions.DependencyInjection#9]
Can a full framework target `net452` or higher be added?

Targetting `netstandard` while trying to use this drags in a lot of packages.

**Comment by tillig** [comment]
It wouldn't make a difference. Even if we did that, [Micrsoft.Extensions.DependencyInjection.Abstractions targets netstandard1.0 only](https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Abstractions/Microsoft.Extensions.DependencyInjection.Abstractions.csproj) so you'd still get the same dependencies.

This is sort of the world we're moving to with .NET Core and the netstandard target framework monikers. I wouldn't worry about the quantity of packages being brought in so much. It's something other frameworks like node.js have been doing for quite some time now. Definitely pros and cons to it, but that's the direction things are headed.

**Comment by adamhathcock** [comment]
It's the .NET Standard Library (which you reference but probably don't need everything) that brings in the dependencies I don't want.  M.E.DI.Abstractions only has two small ones.

I understand the world change but it's not there yet.

**Comment by tillig** [comment]
Referencing the .NET Standard Library is the Microsoft recommended path now rather than specific libraries. [We even turned down a PR on the core Autofac library for the same reason.](https://github.com/autofac/Autofac/pull/783)

**Comment by adamhathcock** [comment]
Actually, it isn't. @terrajobst clarified this on twitter in this thread: https://twitter.com/jbogard/status/837667256112918528

**Comment by adamhathcock** [comment]
Nevermind, I read this the one way.  Ugh.
